# Generated by Django 4.1 on 2024-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ea',
            old_name='firstname',
            new_name='AA',
        ),
        migrations.RenameField(
            model_name='ea',
            old_name='lastname',
            new_name='BA',
        ),
        migrations.AddField(
            model_name='ea',
            name='DA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ea',
            name='TA',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
