# Generated by Django 4.1 on 2024-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('employeeID', models.CharField(max_length=255)),
                ('employee_lastname', models.CharField(max_length=255)),
                ('employee_firstname', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('vacations', models.CharField(max_length=255)),
                ('used_vacations', models.CharField(max_length=255)),
            ],
        ),
    ]
