# Generated by Django 4.1 on 2024-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_remove_todolist_tasks_task_todolist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='todolist',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tasks',
            field=models.ManyToManyField(related_name='todolists', to='TODO.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
