# Generated by Django 4.1 on 2024-08-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_remove_task_todolist_todolist_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TODO.todolist'),
            preserve_default=False,
        ),
    ]
