# Generated by Django 4.1 on 2024-08-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_remove_todolist_tasks_task_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='do_date',
            new_name='due_date',
        ),
    ]
