# Generated by Django 4.1 on 2024-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
